# Generated by Django 3.0.7 on 2020-06-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndealfinder', '0002_restaurant_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='dining_options',
            field=models.ManyToManyField(to='dfndealfinder.DiningType'),
        ),
    ]
