# Generated by Django 3.0.7 on 2020-06-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndealfinder', '0003_auto_20200609_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
