# Generated by Django 3.0.7 on 2020-06-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndealfinder', '0004_auto_20200609_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='special',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='special',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='special',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='special',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='special',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='special',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='special',
            name='special_day',
            field=models.CharField(blank=True, choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], max_length=10, null=True),
        ),
    ]
