# Generated by Django 3.0.7 on 2020-06-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndealfinder', '0005_auto_20200611_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='special',
            name='special_day',
            field=models.CharField(blank=True, choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday'), ('weekdays', 'weekdays'), ('weekends', 'weekends')], max_length=10, null=True),
        ),
    ]
